/********************* ROLES **********************/

/********************* UDFS ***********************/

/****************** GENERATORS ********************/

CREATE GENERATOR DOCUMENTS_ID_SEQ;
CREATE GENERATOR FULLTEXT_ID_SEQ;
/******************** DOMAINS *********************/

/******************* PROCEDURES ******************/

/******************** TABLES **********************/

CREATE TABLE DOCUMENTS
(
  ID INTEGER NOT NULL,
  DOCUMENTNAME VARCHAR(255),
  PATH VARCHAR(1024),
  SCANDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT PK_ID PRIMARY KEY (ID)
);
CREATE TABLE FULLTEXT
(
  ID INTEGER NOT NULL,
  DOCUMENTS_ID INTEGER,
  FULLTEXT BLOB SUB_TYPE 1,
  TEXTTYPE VARCHAR(64),
  CONSTRAINT PK_FULLTEXT_ID PRIMARY KEY (ID)
);
/********************* VIEWS **********************/

/******************* EXCEPTIONS *******************/

/******************** TRIGGERS ********************/

SET TERM ^ ;
CREATE TRIGGER DOCUMENTS_ID_TRIG FOR DOCUMENTS ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
 -- Autoinc emulation:
 IF ((NEW.ID IS NULL) or (NEW.ID=0)) THEN NEW.ID=NEXT VALUE FOR DOCUMENTS_ID_SEQ;
    
END^
SET TERM ; ^
SET TERM ^ ;
CREATE TRIGGER FULLTEXT_ID_TRIG FOR FULLTEXT ACTIVE
BEFORE INSERT POSITION 0
AS 
BEGIN 
 -- Autoinc emulation:
 IF ((NEW.ID IS NULL) or (NEW.ID=0)) THEN NEW.ID=NEXT VALUE FOR FULLTEXT_ID_SEQ;
    
END^
SET TERM ; ^

ALTER TABLE FULLTEXT ADD CONSTRAINT FK_FULLTEXT_DOCUMENTS
  FOREIGN KEY (DOCUMENTS_ID) REFERENCES DOCUMENTS (ID);
GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON DOCUMENTS TO  SYSDBA WITH GRANT OPTION;

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON FULLTEXT TO  SYSDBA WITH GRANT OPTION;

